[package]
name = "day22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file = { path = "../file"}
debug = { path = "../debug"}
regex = "1.11.1"
itertools = "0.13.0"